<a href="https://colab.research.google.com/github/MISHTI100/oibsip_taskno/blob/main/Car_Price_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
data = pd.read_csv('car data.csv')

In [3]:
data

Car_Name  Year  Selling_Price  Present_Price  Driven_kms Fuel_Type  \
0       ritz  2014           3.35           5.59       27000    Petrol   
1        sx4  2013           4.75           9.54       43000    Diesel   
2       ciaz  2017           7.25           9.85        6900    Petrol   
3    wagon r  2011           2.85           4.15        5200    Petrol   
4      swift  2014           4.60           6.87       42450    Diesel   
..       ...   ...            ...            ...         ...       ...   
296     city  2016           9.50          11.60       33988    Diesel   
297     brio  2015           4.00           5.90       60000    Petrol   
298     city  2009           3.35          11.00       87934    Petrol   
299     city  2017          11.50          12.50        9000    Diesel   
300     brio  2016           5.30           5.90        5464    Petrol   

    Selling_type Transmission  Owner  
0         Dealer       Manual      0  
1         Dealer       Manual      0  
2         Dealer       Manual      0  
3         Dealer       Manual      0  
4         Dealer       Manual      0  
..           ...          ...    ...  
296       Dealer       Manual      0  
297       Dealer       Manual      0  
298       Dealer       Manual      0  
299       Dealer       Manual      0  
300       Dealer       Manual      0  

[301 rows x 9 columns]

In [4]:
data.head(10)

Car_Name  Year  Selling_Price  Present_Price  Driven_kms Fuel_Type  \
0           ritz  2014           3.35           5.59       27000    Petrol   
1            sx4  2013           4.75           9.54       43000    Diesel   
2           ciaz  2017           7.25           9.85        6900    Petrol   
3        wagon r  2011           2.85           4.15        5200    Petrol   
4          swift  2014           4.60           6.87       42450    Diesel   
5  vitara brezza  2018           9.25           9.83        2071    Diesel   
6           ciaz  2015           6.75           8.12       18796    Petrol   
7        s cross  2015           6.50           8.61       33429    Diesel   
8           ciaz  2016           8.75           8.89       20273    Diesel   
9           ciaz  2015           7.45           8.92       42367    Diesel   

  Selling_type Transmission  Owner  
0       Dealer       Manual      0  
1       Dealer       Manual      0  
2       Dealer       Manual      0  
3       Dealer       Manual      0  
4       Dealer       Manual      0  
5       Dealer       Manual      0  
6       Dealer       Manual      0  
7       Dealer       Manual      0  
8       Dealer       Manual      0  
9       Dealer       Manual      0

In [5]:
data.tail(10)

Car_Name  Year  Selling_Price  Present_Price  Driven_kms Fuel_Type  \
291     brio  2015           5.40           6.10       31427    Petrol   
292     jazz  2016           6.40           8.40       12000    Petrol   
293     city  2010           3.25           9.90       38000    Petrol   
294    amaze  2014           3.75           6.80       33019    Petrol   
295     city  2015           8.55          13.09       60076    Diesel   
296     city  2016           9.50          11.60       33988    Diesel   
297     brio  2015           4.00           5.90       60000    Petrol   
298     city  2009           3.35          11.00       87934    Petrol   
299     city  2017          11.50          12.50        9000    Diesel   
300     brio  2016           5.30           5.90        5464    Petrol   

    Selling_type Transmission  Owner  
291       Dealer       Manual      0  
292       Dealer       Manual      0  
293       Dealer       Manual      0  
294       Dealer       Manual      0  
295       Dealer       Manual      0  
296       Dealer       Manual      0  
297       Dealer       Manual      0  
298       Dealer       Manual      0  
299       Dealer       Manual      0  
300       Dealer       Manual      0

In [6]:
data.dtypes

Car_Name          object
Year               int64
Selling_Price    float64
Present_Price    float64
Driven_kms         int64
Fuel_Type         object
Selling_type      object
Transmission      object
Owner              int64
dtype: object

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Car_Name       301 non-null    object 
 1   Year           301 non-null    int64  
 2   Selling_Price  301 non-null    float64
 3   Present_Price  301 non-null    float64
 4   Driven_kms     301 non-null    int64  
 5   Fuel_Type      301 non-null    object 
 6   Selling_type   301 non-null    object 
 7   Transmission   301 non-null    object 
 8   Owner          301 non-null    int64  
dtypes: float64(2), int64(3), object(4)
memory usage: 21.3+ KB


In [8]:
data.describe()

Year  Selling_Price  Present_Price     Driven_kms       Owner
count   301.000000     301.000000     301.000000     301.000000  301.000000
mean   2013.627907       4.661296       7.628472   36947.205980    0.043189
std       2.891554       5.082812       8.642584   38886.883882    0.247915
min    2003.000000       0.100000       0.320000     500.000000    0.000000
25%    2012.000000       0.900000       1.200000   15000.000000    0.000000
50%    2014.000000       3.600000       6.400000   32000.000000    0.000000
75%    2016.000000       6.000000       9.900000   48767.000000    0.000000
max    2018.000000      35.000000      92.600000  500000.000000    3.000000

In [9]:
from sklearn.impute import SimpleImputer
imputer_mean = SimpleImputer(missing_values = np.nan, strategy = 'mean')
data[['Selling_Price','Present_Price']] = imputer_mean.fit_transform(data[['Selling_Price','Present_Price']]).astype('object')

In [10]:
data.head(10)

Car_Name  Year Selling_Price Present_Price  Driven_kms Fuel_Type  \
0           ritz  2014          3.35          5.59       27000    Petrol   
1            sx4  2013          4.75          9.54       43000    Diesel   
2           ciaz  2017          7.25          9.85        6900    Petrol   
3        wagon r  2011          2.85          4.15        5200    Petrol   
4          swift  2014           4.6          6.87       42450    Diesel   
5  vitara brezza  2018          9.25          9.83        2071    Diesel   
6           ciaz  2015          6.75          8.12       18796    Petrol   
7        s cross  2015           6.5          8.61       33429    Diesel   
8           ciaz  2016          8.75          8.89       20273    Diesel   
9           ciaz  2015          7.45          8.92       42367    Diesel   

  Selling_type Transmission  Owner  
0       Dealer       Manual      0  
1       Dealer       Manual      0  
2       Dealer       Manual      0  
3       Dealer       Manual      0  
4       Dealer       Manual      0  
5       Dealer       Manual      0  
6       Dealer       Manual      0  
7       Dealer       Manual      0  
8       Dealer       Manual      0  
9       Dealer       Manual      0

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   Car_Name       301 non-null    object
 1   Year           301 non-null    int64 
 2   Selling_Price  301 non-null    object
 3   Present_Price  301 non-null    object
 4   Driven_kms     301 non-null    int64 
 5   Fuel_Type      301 non-null    object
 6   Selling_type   301 non-null    object
 7   Transmission   301 non-null    object
 8   Owner          301 non-null    int64 
dtypes: int64(3), object(6)
memory usage: 21.3+ KB


In [12]:
df = data.drop(columns = ['Car_Name','Year','Fuel_Type','Selling_type','Transmission','Owner'])

In [13]:
df

Selling_Price Present_Price  Driven_kms
0            3.35          5.59       27000
1            4.75          9.54       43000
2            7.25          9.85        6900
3            2.85          4.15        5200
4             4.6          6.87       42450
..            ...           ...         ...
296           9.5          11.6       33988
297           4.0           5.9       60000
298          3.35          11.0       87934
299          11.5          12.5        9000
300           5.3           5.9        5464

[301 rows x 3 columns]

In [16]:
y = df.iloc[:,0].values
x = df.drop(columns = df.columns[0]).values

In [17]:
x

array([[5.59, 27000],
       [9.54, 43000],
       [9.85, 6900],
       [4.15, 5200],
       [6.87, 42450],
       [9.83, 2071],
       [8.12, 18796],
       [8.61, 33429],
       [8.89, 20273],
       [8.92, 42367],
       [3.6, 2135],
       [10.38, 51000],
       [9.94, 15000],
       [7.71, 26000],
       [7.21, 77427],
       [10.79, 43000],
       [10.79, 41678],
       [10.79, 43000],
       [5.09, 35500],
       [7.98, 41442],
       [3.95, 25000],
       [5.71, 2400],
       [8.01, 50000],
       [3.46, 45280],
       [4.41, 56879],
       [4.99, 20000],
       [5.87, 55138],
       [6.49, 16200],
       [3.95, 44542],
       [10.38, 45000],
       [5.98, 51439],
       [4.89, 54200],
       [7.49, 39000],
       [9.95, 45000],
       [8.06, 45000],
       [7.74, 49998],
       [7.2, 48767],
       [2.28, 127000],
       [3.76, 10079],
       [7.98, 62000],
       [7.87, 24524],
       [3.98, 46706],
       [7.15, 58000],
       [8.06, 45780],
       [2.69, 50000],
       [12.

In [18]:
y

array([3.35, 4.75, 7.25, 2.85, 4.6, 9.25, 6.75, 6.5, 8.75, 7.45, 2.85,
       6.85, 7.5, 6.1, 2.25, 7.75, 7.25, 7.75, 3.25, 2.65, 2.85, 4.9, 4.4,
       2.5, 2.9, 3.0, 4.15, 6.0, 1.95, 7.45, 3.1, 2.35, 4.95, 6.0, 5.5,
       2.95, 4.65, 0.35, 3.0, 2.25, 5.85, 2.55, 1.95, 5.5, 1.25, 7.5,
       2.65, 1.05, 5.8, 7.75, 14.9, 23.0, 18.0, 16.0, 2.75, 3.6, 4.5,
       4.75, 4.1, 19.99, 6.95, 4.5, 18.75, 23.5, 33.0, 4.75, 19.75, 9.25,
       4.35, 14.25, 3.95, 4.5, 7.45, 2.65, 4.9, 3.95, 5.5, 1.5, 5.25,
       14.5, 14.73, 4.75, 23.0, 12.5, 3.49, 2.5, 35.0, 5.9, 3.45, 4.75,
       3.8, 11.25, 3.51, 23.0, 4.0, 5.85, 20.75, 17.0, 7.05, 9.65, 1.75,
       1.7, 1.65, 1.45, 1.35, 1.35, 1.35, 1.25, 1.2, 1.2, 1.2, 1.15, 1.15,
       1.15, 1.15, 1.11, 1.1, 1.1, 1.1, 1.05, 1.05, 1.05, 1.05, 1.0, 0.95,
       0.9, 0.9, 0.75, 0.8, 0.78, 0.75, 0.75, 0.75, 0.72, 0.65, 0.65,
       0.65, 0.65, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.55, 0.55,
       0.52, 0.51, 0.5, 0.5, 0.5, 0.5, 0.5, 0.48, 0.48, 0.48, 

In [19]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.25, random_state = 0)

In [20]:
x_train

array([[0.787, 15000],
       [13.6, 29223],
       [2.28, 127000],
       [7.5, 61203],
       [0.54, 14000],
       [18.64, 8700],
       [5.7, 21125],
       [7.5, 44000],
       [8.4, 45078],
       [1.47, 33000],
       [9.4, 32322],
       [14.68, 72000],
       [0.81, 19000],
       [5.9, 5464],
       [0.74, 5000],
       [7.6, 77632],
       [11.8, 9010],
       [2.69, 50000],
       [9.4, 71000],
       [0.57, 25000],
       [0.88, 8000],
       [0.95, 24000],
       [1.6, 1200],
       [10.21, 90000],
       [6.79, 52132],
       [5.09, 35500],
       [0.81, 42000],
       [6.82, 31427],
       [1.75, 11500],
       [0.95, 1300],
       [12.48, 45000],
       [5.35, 53675],
       [9.4, 36000],
       [4.6, 35775],
       [13.6, 10980],
       [4.43, 15000],
       [0.52, 15000],
       [0.826, 23000],
       [9.95, 45000],
       [13.46, 38000],
       [0.81, 11800],
       [8.1, 3435],
       [18.61, 40001],
       [0.84, 23000],
       [7.6, 50456],
       [1.78, 6000],
 

In [21]:
x_test

array([[9.4, 61381],
       [0.826, 6000],
       [5.7, 24678],
       [11.6, 33988],
       [19.77, 15000],
       [5.97, 5600],
       [6.79, 35000],
       [0.55, 1000],
       [6.79, 32000],
       [9.4, 36100],
       [4.6, 22517],
       [0.95, 500],
       [5.7, 20114],
       [9.94, 15000],
       [10.79, 43000],
       [23.15, 11000],
       [8.5, 15059],
       [6.76, 40000],
       [1.05, 30000],
       [1.82, 1400],
       [8.01, 50000],
       [5.7, 3493],
       [9.4, 36198],
       [13.6, 22671],
       [0.75, 60000],
       [0.84, 5000],
       [0.787, 75000],
       [1.2, 23500],
       [0.99, 13000],
       [15.04, 70000],
       [6.79, 58000],
       [9.9, 48000],
       [0.99, 25000],
       [8.89, 20273],
       [10.0, 69562],
       [1.5, 8700],
       [7.7, 16002],
       [7.85, 40000],
       [0.75, 26000],
       [14.0, 63000],
       [9.83, 2071],
       [35.96, 41000],
       [5.7, 4492],
       [7.13, 35866],
       [8.06, 45000],
       [13.6, 35934],
     

In [22]:
y_train

array([0.55, 9.15, 0.35, 2.25, 0.45, 17.0, 4.85, 5.75, 6.45, 1.1, 5.35,
       5.5, 0.6, 5.3, 0.65, 6.0, 8.99, 1.25, 5.2, 0.2, 0.5, 0.45, 1.45,
       2.75, 3.1, 3.25, 0.42, 5.4, 0.95, 0.9, 4.5, 3.0, 5.95, 3.1, 10.11,
       3.15, 0.48, 0.45, 6.0, 12.5, 0.65, 7.9, 6.95, 0.48, 2.1, 1.2, 4.9,
       7.45, 0.4, 7.25, 4.5, 3.95, 1.2, 5.3, 3.1, 4.6, 20.75, 0.42, 4.5,
       9.25, 0.6, 0.1, 0.5, 5.25, 5.85, 0.25, 6.1, 1.25, 0.15, 2.85, 0.45,
       0.9, 2.9, 3.1, 1.5, 6.0, 0.25, 2.65, 10.25, 3.9, 8.35, 14.73, 23.0,
       7.25, 11.25, 1.35, 0.3, 35.0, 2.85, 0.2, 4.1, 2.55, 2.25, 0.48,
       14.9, 2.9, 9.1, 1.0, 4.1, 18.75, 0.2, 4.95, 0.75, 3.25, 6.7, 5.5,
       1.15, 0.6, 0.12, 3.5, 0.51, 1.15, 5.25, 7.05, 4.5, 23.0, 5.75,
       0.45, 4.65, 0.35, 1.15, 3.35, 4.0, 8.65, 5.85, 4.0, 4.0, 5.4,
       14.25, 7.75, 5.8, 2.5, 3.35, 0.6, 5.15, 2.5, 4.0, 0.52, 0.6, 5.25,
       0.3, 1.75, 2.75, 0.75, 4.8, 11.5, 0.17, 6.75, 4.35, 2.95, 3.49,
       0.4, 1.05, 0.6, 8.5, 10.9, 0.6, 8.4, 11.25, 23.0, 

In [23]:
y_test

array([8.25, 0.5, 5.25, 9.5, 18.0, 5.5, 3.75, 0.45, 4.5, 4.5, 2.7, 0.72,
       5.25, 7.5, 7.75, 19.75, 7.4, 4.75, 0.35, 1.7, 4.4, 5.25, 5.11,
       11.25, 0.2, 0.78, 0.38, 0.65, 0.5, 3.6, 3.25, 7.2, 0.6, 8.75, 3.0,
       1.15, 6.6, 4.75, 0.25, 8.25, 9.25, 19.99, 5.5, 4.75, 5.5, 12.9,
       0.3, 1.05, 5.25, 6.5, 7.5, 2.9, 4.8, 23.5, 1.2, 1.1, 0.65, 2.55,
       4.15, 1.35, 3.51, 4.9, 2.0, 33.0, 3.75, 5.65, 8.55, 3.8, 0.4, 2.65,
       2.85, 2.65, 0.48, 6.15, 0.31, 6.0], dtype=object)

In [24]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [25]:
x_train

array([[-7.54101896e-01, -5.54279440e-01],
       [ 6.74064535e-01, -2.10784733e-01],
       [-5.87688684e-01,  2.15059345e+00],
       [-5.85548608e-03,  5.61553079e-01],
       [-7.81633084e-01, -5.78430090e-01],
       [ 1.23583452e+00, -7.06428540e-01],
       [-2.06487623e-01, -4.06356704e-01],
       [-5.85548608e-03,  1.46089433e-01],
       [ 9.44605826e-02,  1.72123835e-01],
       [-6.77973146e-01, -1.19567725e-01],
       [ 2.05922881e-01, -1.35941867e-01],
       [ 7.94443817e-01,  8.22307656e-01],
       [-7.51538263e-01, -4.57676836e-01],
       [-1.84195164e-01, -7.84580046e-01],
       [-7.59340624e-01, -7.95785948e-01],
       [ 5.29074377e-03,  9.58324121e-01],
       [ 4.73432398e-01, -6.98941838e-01],
       [-5.41989142e-01,  2.90993338e-01],
       [ 2.05922881e-01,  7.98157005e-01],
       [-7.78289215e-01, -3.12772932e-01],
       [-7.43735902e-01, -7.23333995e-01],
       [-7.35933542e-01, -3.36923582e-01],
       [-6.63483047e-01, -8.87558421e-01],
       [ 2.

In [26]:
x_test

array([[ 2.05799977e-01,  9.23056835e-01],
       [-9.35026943e-01, -9.42269588e-01],
       [-2.86509284e-01, -3.13162729e-01],
       [ 4.98524403e-01,  4.13930409e-04],
       [ 1.58559647e+00, -6.39134256e-01],
       [-2.50584013e-01, -9.55742269e-01],
       [-1.41477637e-01,  3.44998144e-02],
       [-9.71750553e-01, -1.11067811e+00],
       [-1.41477637e-01, -6.65452962e-02],
       [ 2.05799977e-01,  7.15496883e-02],
       [-4.32871497e-01, -3.85948891e-01],
       [-9.18527930e-01, -1.12751896e+00],
       [-2.86509284e-01, -4.66886024e-01],
       [ 2.77650518e-01, -6.39134256e-01],
       [ 3.90748592e-01,  3.03953443e-01],
       [ 2.03532764e+00, -7.73861070e-01],
       [ 8.60490761e-02, -6.37147036e-01],
       [-1.45469333e-01,  2.02908332e-01],
       [-9.05222274e-01, -1.33908703e-01],
       [-8.02768725e-01, -1.09720542e+00],
       [ 2.08513631e-02,  5.39725367e-01],
       [-2.86509284e-01, -1.02670962e+00],
       [ 2.05799977e-01,  7.48504952e-02],
       [ 7.

In [27]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x_train, y_train)

LinearRegression()

In [28]:
y_pred = model.predict(x_test)

In [29]:
model.predict([[5.59,	27000]])

array([-18809.38402424])

In [30]:
model.predict([[4.15,	5200]])

array([-3605.3675198])

In [31]:
model.predict([[5.9,	60000]])

array([-41832.90380912])