<a href="https://colab.research.google.com/github/MISHTI100/oibsip_taskno/blob/main/Unemployment_India.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
data = pd.read_csv('unemployment India.csv')

In [3]:
data

Region         Date  Frequency   Estimated Unemployment Rate (%)  \
0    Andhra Pradesh   31-05-2019    Monthly                              3.65   
1    Andhra Pradesh   30-06-2019    Monthly                              3.05   
2    Andhra Pradesh   31-07-2019    Monthly                              3.75   
3    Andhra Pradesh   31-08-2019    Monthly                              3.32   
4    Andhra Pradesh   30-09-2019    Monthly                              5.17   
..              ...          ...        ...                               ...   
749     West Bengal   29-02-2020    Monthly                              7.55   
750     West Bengal   31-03-2020    Monthly                              6.67   
751     West Bengal   30-04-2020    Monthly                             15.63   
752     West Bengal   31-05-2020    Monthly                             15.22   
753     West Bengal   30-06-2020    Monthly                              9.86   

      Estimated Employed   Estimated Labour Participation Rate (%)   Area  
0             11999139.0                                     43.24  Rural  
1             11755881.0                                     42.05  Rural  
2             12086707.0                                     43.50  Rural  
3             12285693.0                                     43.97  Rural  
4             12256762.0                                     44.68  Rural  
..                   ...                                       ...    ...  
749           10871168.0                                     44.09  Urban  
750           10806105.0                                     43.34  Urban  
751            9299466.0                                     41.20  Urban  
752            9240903.0                                     40.67  Urban  
753            9088931.0                                     37.57  Urban  

[754 rows x 7 columns]

In [4]:
data.dtypes

Region                                       object
 Date                                        object
 Frequency                                   object
 Estimated Unemployment Rate (%)            float64
 Estimated Employed                         float64
 Estimated Labour Participation Rate (%)    float64
Area                                         object
dtype: object

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 754 entries, 0 to 753
Data columns (total 7 columns):
 #   Column                                    Non-Null Count  Dtype  
---  ------                                    --------------  -----  
 0   Region                                    740 non-null    object 
 1    Date                                     740 non-null    object 
 2    Frequency                                740 non-null    object 
 3    Estimated Unemployment Rate (%)          740 non-null    float64
 4    Estimated Employed                       740 non-null    float64
 5    Estimated Labour Participation Rate (%)  740 non-null    float64
 6   Area                                      740 non-null    object 
dtypes: float64(3), object(4)
memory usage: 41.4+ KB


In [14]:
data.describe()

Estimated Unemployment Rate (%)   Estimated Employed  \
count                        740.000000         7.400000e+02   
mean                          11.787946         7.204460e+06   
std                           10.721298         8.087988e+06   
min                            0.000000         4.942000e+04   
25%                            4.657500         1.190404e+06   
50%                            8.350000         4.744178e+06   
75%                           15.887500         1.127549e+07   
max                           76.740000         4.577751e+07   

        Estimated Labour Participation Rate (%)  
count                                740.000000  
mean                                  42.630122  
std                                    8.111094  
min                                   13.330000  
25%                                   38.062500  
50%                                   41.160000  
75%                                   45.505000  
max                                   72.570000

In [9]:
data.columns

Index(['Region', ' Date', ' Frequency', ' Estimated Unemployment Rate (%)',
       ' Estimated Employed', ' Estimated Labour Participation Rate (%)',
       'Area'],
      dtype='object')

In [67]:
df = data.drop(columns = ['Region','Area'])

In [13]:
df

Date  Frequency   Estimated Unemployment Rate (%)  \
0     31-05-2019    Monthly                              3.65   
1     30-06-2019    Monthly                              3.05   
2     31-07-2019    Monthly                              3.75   
3     31-08-2019    Monthly                              3.32   
4     30-09-2019    Monthly                              5.17   
..           ...        ...                               ...   
749   29-02-2020    Monthly                              7.55   
750   31-03-2020    Monthly                              6.67   
751   30-04-2020    Monthly                             15.63   
752   31-05-2020    Monthly                             15.22   
753   30-06-2020    Monthly                              9.86   

      Estimated Employed   Estimated Labour Participation Rate (%)  
0             11999139.0                                     43.24  
1             11755881.0                                     42.05  
2             12086707.0                                     43.50  
3             12285693.0                                     43.97  
4             12256762.0                                     44.68  
..                   ...                                       ...  
749           10871168.0                                     44.09  
750           10806105.0                                     43.34  
751            9299466.0                                     41.20  
752            9240903.0                                     40.67  
753            9088931.0                                     37.57  

[754 rows x 5 columns]

In [18]:
from sklearn.impute import SimpleImputer
imputer_mean = SimpleImputer(missing_values = np.nan, strategy = 'mean')
df[[' Estimated Unemployment Rate (%)',
       ' Estimated Employed', ' Estimated Labour Participation Rate (%)',]] = imputer_mean.fit_transform(df[[' Estimated Unemployment Rate (%)',
       ' Estimated Employed', ' Estimated Labour Participation Rate (%)']]).astype('object')

In [19]:
df.head(10)

Date  Frequency  Estimated Unemployment Rate (%)  \
0   31-05-2019    Monthly                             3.65   
1   30-06-2019    Monthly                             3.05   
2   31-07-2019    Monthly                             3.75   
3   31-08-2019    Monthly                             3.32   
4   30-09-2019    Monthly                             5.17   
5   31-10-2019    Monthly                             3.52   
6   30-11-2019    Monthly                             4.12   
7   31-12-2019    Monthly                             4.38   
8   31-01-2020    Monthly                             4.84   
9   29-02-2020    Monthly                             5.91   

   Estimated Employed  Estimated Labour Participation Rate (%)  
0          11999139.0                                    43.24  
1          11755881.0                                    42.05  
2          12086707.0                                     43.5  
3          12285693.0                                    43.97  
4          12256762.0                                    44.68  
5          12017412.0                                    43.01  
6          11397681.0                                     41.0  
7          12528395.0                                    45.14  
8          12016676.0                                    43.46  
9          11723617.0                                    42.83

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 754 entries, 0 to 753
Data columns (total 5 columns):
 #   Column                                    Non-Null Count  Dtype 
---  ------                                    --------------  ----- 
 0    Date                                     740 non-null    object
 1    Frequency                                740 non-null    object
 2    Estimated Unemployment Rate (%)          754 non-null    object
 3    Estimated Employed                       754 non-null    object
 4    Estimated Labour Participation Rate (%)  754 non-null    object
dtypes: object(5)
memory usage: 29.6+ KB


In [22]:
df[[' Estimated Unemployment Rate (%)',
       ' Estimated Employed', ' Estimated Labour Participation Rate (%)']] = df[[' Estimated Unemployment Rate (%)',
       ' Estimated Employed', ' Estimated Labour Participation Rate (%)']].astype("float")

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 754 entries, 0 to 753
Data columns (total 5 columns):
 #   Column                                    Non-Null Count  Dtype  
---  ------                                    --------------  -----  
 0    Date                                     740 non-null    object 
 1    Frequency                                740 non-null    object 
 2    Estimated Unemployment Rate (%)          754 non-null    float64
 3    Estimated Employed                       754 non-null    float64
 4    Estimated Labour Participation Rate (%)  754 non-null    float64
dtypes: float64(3), object(2)
memory usage: 29.6+ KB


In [66]:
df_new = data.drop(columns = [' Date',' Frequency','Region','Area'])

In [68]:
df_new

Estimated Unemployment Rate (%)  Estimated Employed  \
0                               3.65          11999139.0   
1                               3.05          11755881.0   
2                               3.75          12086707.0   
3                               3.32          12285693.0   
4                               5.17          12256762.0   
..                               ...                 ...   
749                             7.55          10871168.0   
750                             6.67          10806105.0   
751                            15.63           9299466.0   
752                            15.22           9240903.0   
753                             9.86           9088931.0   

     Estimated Labour Participation Rate (%)  
0                                      43.24  
1                                      42.05  
2                                       43.5  
3                                      43.97  
4                                      44.68  
..                                       ...  
749                                    44.09  
750                                    43.34  
751                                     41.2  
752                                    40.67  
753                                    37.57  

[754 rows x 3 columns]

In [69]:
y = df_new.iloc[:,1].values
x = df_new.drop(columns = df_new.columns[1]).values

In [70]:
x

array([[3.65, 43.24],
       [3.05, 42.05],
       [3.75, 43.5],
       ...,
       [15.63, 41.2],
       [15.22, 40.67],
       [9.86, 37.57]], dtype=object)

In [71]:
y

array([11999139.0, 11755881.0, 12086707.0, 12285693.0, 12256762.0,
       12017412.0, 11397681.0, 12528395.0, 12016676.0, 11723617.0,
       11359660.0, 8792827.0, 9526902.0, 15572975.0, 11749334.0,
       8923222.0, 9911534.0, 9292039.0, 11468349.0, 8395906.0, 9625362.0,
       11420996.0, 8462814.0, 9878742.0, 9926176.0, 7544937.0, 24322330.0,
       24097712.0, 23248875.0, 22260203.0, 23905700.0, 24053140.0,
       22445989.0, 22914530.0, 23409006.0, 23168192.0, 22667882.0,
       14645275.0, 14050319.0, 20622566.0, 6259019.0, 6608626.0,
       6753622.0, 6607694.0, 6490776.0, 7043840.0, 6942931.0, 6569385.0,
       6236201.0, 6847173.0, 6894808.0, 6534321.0, 5454091.0, 5781095.0,
       169487.0, 149076.0, 166605.0, 135407.0, 166056.0, 149511.0,
       178768.0, 145671.0, 157791.0, 147500.0, 152413.0, 115487.0,
       129610.0, 112108.0, 179340.0, 170471.0, 167437.0, 183603.0,
       163215.0, 177440.0, 159489.0, 177155.0, 158936.0, 171672.0,
       181657.0, 128538.0, 13954728.0, 

In [72]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.25, random_state = 0)

In [73]:
x_train

array([[76.74, 35.54],
       [9.61, 37.28],
       [4.9, 31.97],
       ...,
       [4.55, 29.73],
       [30.28, 29.95],
       [1.52, 44.59]], dtype=object)

In [74]:
x_test

array([[12.63, 39.15],
       [27.47, 56.17],
       [17.66, 38.03],
       [20.0, 33.71],
       [8.33, 35.19],
       [9.82, 42.89],
       [16.11, 43.02],
       [10.2, 39.71],
       [25.59, 58.8],
       [8.91, 38.84],
       [10.71, 32.0],
       [9.4, 48.34],
       [5.77, 40.31],
       [4.29, 57.39],
       [9.0, 42.19],
       [1.8, 63.18],
       [12.47, 40.31],
       [7.83, 43.25],
       [24.19, 39.87],
       [24.67, 43.18],
       [11.787945945945948, 42.630121621621626],
       [14.91, 36.29],
       [46.89, 35.48],
       [0.0, 43.34],
       [3.8, 36.76],
       [9.14, 33.24],
       [11.787945945945948, 42.630121621621626],
       [6.31, 44.57],
       [3.63, 37.97],
       [2.39, 40.85],
       [45.78, 28.28],
       [40.59, 41.14],
       [8.21, 47.39],
       [4.09, 41.67],
       [27.19, 45.37],
       [11.787945945945948, 42.630121621621626],
       [4.84, 43.46],
       [10.26, 39.96],
       [7.88, 38.61],
       [12.78, 40.57],
       [14.06, 38.45],
       

In [75]:
y_train

array([68122.0, 23168192.0, 243277.0, 142176.0, 1551007.0, 171672.0,
       7204460.025675676, 49420.0, 2326911.0, 1957081.0, 6189471.0,
       830347.0, 4603484.0, 316887.0, 1057975.0, 172474.0, 15040572.0,
       312548.0, 9088931.0, 1664145.0, 7204460.025675676, 11456493.0,
       6088547.0, 1229406.0, 4062767.0, 5400499.0, 16748971.0, 44257432.0,
       1441722.0, 23409006.0, 8822411.0, 1106978.0, 10806105.0, 6164215.0,
       280367.0, 310342.0, 13938874.0, 162426.0, 17396398.0, 17122782.0,
       675083.0, 15014802.0, 42276572.0, 8799249.0, 4306807.0, 9526902.0,
       5184355.0, 6260971.0, 11902824.0, 245668.0, 15828488.0, 2404033.0,
       10626328.0, 5432503.0, 279839.0, 9683719.0, 181657.0, 11121124.0,
       2460196.0, 129610.0, 5313236.0, 4822035.0, 3003787.0, 348042.0,
       5668785.0, 11304474.0, 2298975.0, 76269.0, 75456.0, 8923222.0,
       6308129.0, 1226793.0, 11397681.0, 2021553.0, 937435.0, 4366148.0,
       16715470.0, 1595176.0, 328282.0, 13483615.0, 236315.0, 15

In [76]:
y_test

array([5176819.0, 391015.0, 2994763.0, 128538.0, 311146.0, 6259019.0,
       5439600.0, 24097712.0, 408738.0, 5203579.0, 1675441.0, 23601016.0,
       81905.0, 11749334.0, 5605627.0, 1102997.0, 24053140.0, 10563686.0,
       2523005.0, 2693596.0, 7204460.025675676, 2977857.0, 1606580.0,
       175718.0, 4824630.0, 4079775.0, 7204460.025675676, 10144965.0,
       15349838.0, 12853818.0, 2343783.0, 3727366.0, 2407509.0, 9686558.0,
       4570108.0, 7204460.025675676, 12016676.0, 43287808.0, 4913963.0,
       2495186.0, 3173429.0, 13099601.0, 6834930.0, 177155.0, 15356938.0,
       261687.0, 294379.0, 1054829.0, 11755881.0, 41908909.0, 2347941.0,
       149076.0, 5109481.0, 5157363.0, 14610564.0, 86186.0, 4657443.0,
       26357625.0, 12674451.0, 180283.0, 3378431.0, 1946957.0, 9299466.0,
       25543465.0, 3575778.0, 6787403.0, 16463931.0, 1303244.0, 2290170.0,
       15419779.0, 2594469.0, 327239.0, 235894.0, 5401392.0, 1754170.0,
       2179106.0, 5195170.0, 1052597.0, 253887.0, 138285

In [77]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [78]:
x_train

array([[ 6.05775502, -0.86827477],
       [-0.18482809, -0.65184567],
       [-0.62282253, -1.31232757],
       ...,
       [-0.65536988, -1.59094894],
       [ 1.73732583, -1.56358434],
       [-0.937137  ,  0.25740531]])

In [79]:
x_test

array([[ 0.02684909, -0.47640752],
       [ 1.48681124,  1.65312515],
       [ 0.52170149, -0.61654128],
       [ 0.75191115, -1.15705721],
       [-0.39618577, -0.97188046],
       [-0.24959927, -0.00846086],
       [ 0.36921218,  0.00780467],
       [-0.2122148 , -0.40634064],
       [ 1.30185647,  1.98218924],
       [-0.33912525, -0.51519454],
       [-0.1620409 , -1.37101143],
       [-0.29091896,  0.67344002],
       [-0.64803908, -0.33126898],
       [-0.79364178,  1.80577085],
       [-0.33027104, -0.09604446],
       [-1.03860847,  2.53021234],
       [ 0.01110825, -0.33126898],
       [-0.44537587,  0.03658214],
       [ 1.16412419, -0.38632153],
       [ 1.21134668,  0.02782378],
       [-0.05599236, -0.04097669],
       [ 0.25115594, -0.83424909],
       [ 3.39735471, -0.93559582],
       [-1.21569283,  0.04784288],
       [-0.84184807, -0.77544295],
       [-0.31649781, -1.21586334],
       [-0.05599236, -0.04097669],
       [-0.59491377,  0.20173978],
       [-0.85857271,

In [81]:
from sklearn.decomposition import PCA
pca = PCA(n_components = 2)
x_pca = pca.fit_transform(x)

In [83]:
df_new

Estimated Unemployment Rate (%)  Estimated Employed  \
0                               3.65          11999139.0   
1                               3.05          11755881.0   
2                               3.75          12086707.0   
3                               3.32          12285693.0   
4                               5.17          12256762.0   
..                               ...                 ...   
749                             7.55          10871168.0   
750                             6.67          10806105.0   
751                            15.63           9299466.0   
752                            15.22           9240903.0   
753                             9.86           9088931.0   

     Estimated Labour Participation Rate (%)  
0                                      43.24  
1                                      42.05  
2                                       43.5  
3                                      43.97  
4                                      44.68  
..                                       ...  
749                                    44.09  
750                                    43.34  
751                                     41.2  
752                                    40.67  
753                                    37.57  

[754 rows x 3 columns]

In [84]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x_train, y_train)

LinearRegression()

In [86]:
y_pred = model.predict(x_test)

In [91]:
model.predict([[11999139.0,	43.24]])

array([-2.23581982e+13])

In [92]:
model.predict([[10871168.0,	44.09]])

array([-2.02564298e+13])

In [93]:
model.predict([[9299466.0,	41.2]])

array([-1.73278499e+13])